name: ews_flutter
description: Elephant Warning System (EWS) - Coimbatore Forest Division. Field, command centre and analytics app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  pdf: ^3.13.1
  printing: ^5.15.1
 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  fl_chart: ^0.69.0
  sembast: ^3.8.11
  sembast_web: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/maps/forest_boundaries.json
